language: python
python:
    - 2.7
    - 3.5
    - 3.6
install:
    - virtualenv env
    - env/bin/pip install -U setuptools
    - env/bin/python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
